### PR TITLE
WebExtensions compatibility and deploy automation

### PR DESCRIPTION
**Pull request by Narno**
Changes:
- add [xo](https://github.com/sindresorhus/xo) test
- add Gulp build / release file
- add Travis config + autodeploy
- move Chrome source code in "src/"
- delete old Firefox extension code (deprecated)
- clean Git ignore file

2 goals with this PR:
1. WebExtension: Turn the extension compatible with [WebExtensions](https://developer.mozilla.org/Add-ons/WebExtensions), and available for Firefox
2. Automation: automatically build and deploy extension to stores with Travis

### CODE REVIEW

**Comment by Narno** [comment]
@tristen, to build and deploy automatically with Travis, we need Chrome Webstore credentials:
- `CLIENT_ID`
- `CLIENT_SECRET`

@tristen @ajsb85, if you want the same for the Firefox module, we need AMO API credentials:
- `WEB_EXT_API_KEY`
- `WEB_EXT_API_SECRET`

**Comment by ajsb85** [comment]
Hi, @Narno 

You can request the credentials here:

https://addons.mozilla.org/en-US/developers/addon/api/key/

image

**Comment by Narno** [comment]
Thanks a lot @ajsb85, configuration in progress! 👍 
prose browser extensions travis ci

@tristen, could you enable Travis for the repository please?
prose profile travis ci

**Comment by Narno** [comment]
Thanks a lot @tristen! \o/

To achieve the automation on Chrome Webstore, could you create credential and/or give me access to the extension dashboard?

**Set up Group Publishing**
https://developer.chrome.com/webstore/publish#set-up-group-publishing

**Enable API**
developer.chrome.com/webstore/using_webstore_api

**Add env. variables to Travis**
https://www.travis-ci.org/prose/browser-extensions/settings  
`CLIENT_ID` and `CLIENT_SECRET`

**Comment by tristen** [comment]
@Narno I've created group publishing and added the email address in your github profile to it. Is that enough for you to gain access to those variables and add them to Travis?

**Comment by Narno** [comment]
@tristen seen the notification, but could you use my Gmail address please? (arnaud{dot}ligny{at}gmail{dot}com)

**Comment by Narno** [comment]
@tristen, I think my user is not allowed to publish in the name of the "prose" group:
> cd build && webstore upload --auto-publish
> Response code 400 (Bad Request)
> {
>     "error": "invalid_user"
> }

Maybe I must be "co-owner" of the group or something like that :-/

**Pull request merged**
